/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college.information.system;

import java.awt.print.PrinterException;
import java.sql.*;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author iamro_6xt76lq
 */
public class NewStudent extends javax.swing.JInternalFrame {

    /**
     * Creates new form iframe1
     */
    public NewStudent() {
        initComponents();
    }
    public void refresh(){
        Sname.setText("");
        Fname.setText("");
        Mname.setText("");
        ADCno.setText("");
        Contact.setText("");
        DOB.setText("");
        Dept.setSelectedItem("");
        
        address.setText("");
        course.setSelectedItem("");
        email.setText("");
        mark10.setText("");
        mark12.setText("");
        roll10.setText("");
        roll12.setText("");
        male1.setSelected(false);
        female.setSelected(false);
        this.requestFocus();
    }
    
    
    
    Connection conn;
    PreparedStatement pst;
    String SelectedCourse, SelectedDept;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Sname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mark12 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Dept = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Mname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ADCno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Contact = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        roll10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        mark10 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        roll12 = new javax.swing.JTextField();
        male1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();

        setBorder(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(null);
        setName(""); // NOI18N
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Student Name ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));
        getContentPane().add(Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 190, -1));

        jLabel2.setText("Contact Number ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, -1));

        mark12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark12ActionPerformed(evt);
            }
        });
        getContentPane().add(mark12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 190, -1));

        jLabel3.setText("Date Of Birth");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel5.setText("Course");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BA", "BCA", "B.com", "Bsc" }));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jLabel6.setText("Department ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BFC", "BFCMT", "BFCET" }));
        Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptActionPerformed(evt);
            }
        });
        getContentPane().add(Dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 120, 40));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 130, 40));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 320, 20));

        jLabel10.setText("E-mail");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        address.setColumns(14);
        address.setRows(3);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 200, 70));

        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, -1, -1));

        jLabel12.setText("Father's Name ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, -1));

        Mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnameActionPerformed(evt);
            }
        });
        Mname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MnameKeyPressed(evt);
            }
        });
        getContentPane().add(Mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 190, -1));

        jLabel13.setText("Mother's Name ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        ADCno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADCnoActionPerformed(evt);
            }
        });
        getContentPane().add(ADCno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 190, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel15.setText("Education Detail");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 190, 40));

        jLabel7.setText("ADHAAR CARD NO.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));
        getContentPane().add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, 190, -1));

        jLabel22.setText("10th Roll No.");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactActionPerformed(evt);
            }
        });
        getContentPane().add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 190, -1));

        jLabel23.setText("12th Marks");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 160, 190, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel16.setText("Contact Detail");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 210, 60));

        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 190, -1));

        roll10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roll10ActionPerformed(evt);
            }
        });
        getContentPane().add(roll10, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, 190, -1));

        jLabel24.setText("10th marks");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        mark10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark10ActionPerformed(evt);
            }
        });
        getContentPane().add(mark10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 190, -1));

        jLabel25.setText("12th Roll No.");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, -1, -1));

        roll12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roll12ActionPerformed(evt);
            }
        });
        getContentPane().add(roll12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 190, -1));

        male1.setText("Male");
        male1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male1ActionPerformed(evt);
            }
        });
        getContentPane().add(male1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 640));

        setBounds(0, 0, 1358, 668);
    }// </editor-fold>//GEN-END:initComponents

    private void mark12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String StudentName = Sname.getText();
        String FatherName = Fname.getText();
        String MotherName = Mname.getText();
        String DOfB = DOB.getText();
        String ContactNo = Contact.getText();
        String Email = email.getText();
        String Gender = male1.isSelected()?"Male":"Female";
        String Address = address.getText();
        String AdhaarCard = ADCno.getText();
        String Marks10 = mark10.getText();
        String Marks12 = mark12.getText();
        String RollNo10 = roll10.getText();
        String RollNo12 = roll12.getText();
        String Course = (String) course.getSelectedItem();
        String Department = (String) course.getSelectedItem();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            conn = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\iamro_6xt76lq\\Documents\\NetBeansProjects\\College Information System\\dbcis.accdb");//Establishing Connection
            System.out.println("Connected Successfully");
            pst = conn.prepareStatement("insert into Student_table(StudentName, FatherName, MotherName, ContactNo, DOB, Gender, Email, Address, AdhaarCard, 10thMarks, 12thMarks, 10thRollNo, 12thRollNo, Course, Department)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, StudentName);
            pst.setString(2, FatherName);
            pst.setString(3, MotherName);
            pst.setString(4, ContactNo);
            pst.setString(5, DOfB);
            pst.setString(6, Gender);
            pst.setString(7, Email);
            pst.setString(8, Address);
            pst.setString(9, AdhaarCard);
            pst.setString(10, Marks10);
            pst.setString(11, Marks12);
            pst.setString(12, RollNo10);
            pst.setString(13, RollNo12);
            pst.setString(14, Course);
            pst.setString(15, Department);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "record added");
            refresh();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameDeiconified

    private void MnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnameActionPerformed

    private void ADCnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADCnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADCnoActionPerformed

    private void ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void roll10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roll10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roll10ActionPerformed

    private void mark10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark10ActionPerformed

    private void roll12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roll12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roll12ActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        if (female.isSelected()) {
            male1.setSelected(false);
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void male1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male1ActionPerformed
        // TODO add your handling code here:
        if (male1.isSelected()) {
            female.setSelected(false);
        }
    }//GEN-LAST:event_male1ActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
        SelectedCourse = course.getSelectedItem().toString();
    }//GEN-LAST:event_courseActionPerformed

    private void DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptActionPerformed
        // TODO add your handling code here:
        SelectedDept = Dept.getSelectedItem().toString();
    }//GEN-LAST:event_DeptActionPerformed

    private void MnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADCno;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField DOB;
    private javax.swing.JComboBox<String> Dept;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Mname;
    private javax.swing.JTextField Sname;
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male1;
    private javax.swing.JTextField mark10;
    private javax.swing.JTextField mark12;
    private javax.swing.JTextField roll10;
    private javax.swing.JTextField roll12;
    // End of variables declaration//GEN-END:variables

    private void print() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
