/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college.information.system;

import java.awt.print.PrinterException;
import java.sql.DriverManager;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author iamro_6xt76lq
 */
public class SearchStudent extends javax.swing.JInternalFrame {

    /**
     * Creates new form iframe1
     */
    public SearchStudent() {
        initComponents();
        tableupdate();
    }
    
    
    public void tableclick(){
        
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        Sid.setText(dummyRows.get(selectedIndex).get(0));
        Sname.setText(dummyRows.get(selectedIndex).get(1));
        DOB.setText(dummyRows.get(selectedIndex).get(2));
        Fname.setText(dummyRows.get(selectedIndex).get(4));
        Contact.setText(dummyRows.get(selectedIndex).get(6));
        mail.setText(dummyRows.get(selectedIndex).get(8));
        ADCno.setText(dummyRows.get(selectedIndex).get(9));
        String Gender;
        Gender = dummyRows.get(selectedIndex).get(7);
                if ("Male".equals(Gender))
                male1.setSelected(true);
                else
                    female.setSelected(true); 
        Mname.setText(dummyRows.get(selectedIndex).get(5));
        mark10.setText(dummyRows.get(selectedIndex).get(10));
        mark12.setText(dummyRows.get(selectedIndex).get(11));
        roll10.setText(dummyRows.get(selectedIndex).get(12));
        roll12.setText(dummyRows.get(selectedIndex).get(13));
        address.setText(dummyRows.get(selectedIndex).get(16));
        course.setSelectedItem(dummyRows.get(selectedIndex).get(14));
        Dept.setSelectedItem(dummyRows.get(selectedIndex).get(15));
        
        txtprint.append("\t Student Record \n\n" +
                "=============================================="+"\n\n"+
                "Student Id:\t\t"+ Sid.getText()+ "\n" + 
                "Student name:\t\t" + Sname.getText() +"\n" +
                "Father Name:\t\t" + Fname.getText()+"\n" +
                "Course Applied for \t"+ course.getSelectedItem()+"\n" +
                "=============================================="
                );
        
    }
    
    public void search(String str){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //int selectedIndex = jTable1.getSelectedRow();
       // int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        jTable1.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
    
    
    public void refresh(){
        Sname.setText("");
        Fname.setText("");
        Mname.setText("");
        ADCno.setText("");
        Contact.setText("");
        DOB.setText("");
        Dept.setSelectedItem("");
        Sid.setText("");
        address.setText("");
        course.setSelectedItem("");
        mail.setText("");
        mark10.setText("");
        mark12.setText("");
        roll10.setText("");
        roll12.setText("");
        male1.setSelected(false);
        female.setSelected(false);
        this.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Vector<Vector<String>> dummyRows = new Vector<Vector<String>>();

    @SuppressWarnings("unchecked")
    Connection conn;
    PreparedStatement pst, psd;
    ResultSet rs, rsf = null;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Sname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Mname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ADCno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        Contact = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Sid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        searchname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        male1 = new javax.swing.JRadioButton();
        DOB = new javax.swing.JTextField();
        mark12 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        Dept = new javax.swing.JComboBox<>();
        id = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        roll10 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        mark10 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        roll12 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();

        setBorder(null);
        setClosable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon("C:\\Users\\iamro_6xt76lq\\Desktop\\update icon.png")); // NOI18N
        setName(""); // NOI18N
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Student Name ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));
        getContentPane().add(Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 190, -1));

        jLabel2.setText("Contact Number ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        jLabel3.setText("Date Of Birth");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));

        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        Update.setText("Update Details");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 120, 40));

        jButton2.setText("Delete Record");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 530, 130, 40));

        jLabel10.setText("E-mail");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        address.setColumns(14);
        address.setRows(3);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 200, -1));

        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        jLabel12.setText("Father's Name ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        Mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnameActionPerformed(evt);
            }
        });
        getContentPane().add(Mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 190, -1));

        jLabel13.setText("Mother's Name ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        ADCno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADCnoActionPerformed(evt);
            }
        });
        getContentPane().add(ADCno, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 190, -1));

        jLabel7.setText("ADHAAR CARD NO.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));
        getContentPane().add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 190, -1));

        Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactActionPerformed(evt);
            }
        });
        getContentPane().add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 190, -1));

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 190, -1));

        jLabel8.setText("Student ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        Sid.setEditable(false);
        getContentPane().add(Sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 190, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "DOB", "Course"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 440, 320));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Search Student");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 60));

        searchname.setText("Seach by Name...");
        searchname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchnameMouseClicked(evt);
            }
        });
        searchname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnameActionPerformed(evt);
            }
        });
        searchname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchnameKeyReleased(evt);
            }
        });
        jPanel1.add(searchname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Student Name");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 630));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel17.setText("Contact Detail");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 210, 70));

        male1.setText("Male");
        male1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male1ActionPerformed(evt);
            }
        });
        getContentPane().add(male1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, -1));

        DOB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOBMouseClicked(evt);
            }
        });
        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 190, -1));

        mark12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark12ActionPerformed(evt);
            }
        });
        getContentPane().add(mark12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 190, -1));

        jLabel20.setText("Course");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, -1, -1));

        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BA", "BCA", "B.com", "Bsc" }));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 180, -1, -1));

        jLabel21.setText("Department ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, -1, -1));

        Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BFC", "BFCMT", "BFCET" }));
        Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptActionPerformed(evt);
            }
        });
        getContentPane().add(Dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, -1, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 320, 20));

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel26.setText("Education Detail");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 240, 70));

        jLabel28.setText("10th Roll No.");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, -1, -1));

        jLabel29.setText("12th Marks");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, -1, -1));

        roll10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roll10ActionPerformed(evt);
            }
        });
        getContentPane().add(roll10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 280, 190, -1));

        jLabel31.setText("10th marks");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, -1, -1));

        mark10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark10ActionPerformed(evt);
            }
        });
        getContentPane().add(mark10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 110, 190, -1));

        jLabel32.setText("12th Roll No.");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, -1, -1));

        roll12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roll12ActionPerformed(evt);
            }
        });
        getContentPane().add(roll12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 310, 190, -1));

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 120, 40));

        txtprint.setEditable(false);
        txtprint.setColumns(20);
        txtprint.setRows(5);
        txtprint.setOpaque(false);
        jScrollPane3.setViewportView(txtprint);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 300, 130));

        setBounds(0, 0, 1350, 668);
    }// </editor-fold>//GEN-END:initComponents

    dbconnect obj = new dbconnect();

    public void tableupdate() {
        int c;
        obj.conn();
        this.conn=obj.connection;
        rs = obj.search();
        try {
            Vector<Vector<String>> rows = new Vector<Vector<String>>();
            Vector<String> columns = new Vector<String>();
//            v2.add(rs.getString("id"));
//            v2.add(rs.getString("StudentName"));
//            v2.add(rs.getString("DOB"));
//            v2.add(rs.getString("Course"));
//            v2.add(rs.getString("FatherName"));
//            v2.add(rs.getString("MotherName"));
//            v2.add(rs.getString("ContactNo"));
//            v2.add(rs.getString("Gender"));
//            v2.add(rs.getString("EMail"));
//            v2.add(rs.getString("AdhaarCard"));

            while (rs.next()) {
                Vector<String> v2 = new Vector<String>();
                Vector<String> v1 = new Vector<String>();
                v1.add(rs.getString("id"));
                v1.add(rs.getString("StudentName"));
                v1.add(rs.getString("DOB"));
                v1.add(rs.getString("Course"));
                v2.add(rs.getString("id"));
                v2.add(rs.getString("StudentName"));
                v2.add(rs.getString("DOB"));
                v2.add(rs.getString("Course"));

                v2.add(rs.getString("FatherName"));
                v2.add(rs.getString("MotherName"));
                v2.add(rs.getString("ContactNo"));
                v2.add(rs.getString("Gender"));
                v2.add(rs.getString("EMail"));
                v2.add(rs.getString("AdhaarCard"));
                v2.add(rs.getString("10thMarks"));
                v2.add(rs.getString("12thMarks"));
                v2.add(rs.getString("10thRollNo"));
                v2.add(rs.getString("12thRollNo"));
                v2.add(rs.getString("Course"));
                
                v2.add(rs.getString("Department"));
                v2.add(rs.getString("Address"));
                rows.add(v1);
                dummyRows.add(v2);
            }
            columns.add("id");
            columns.add("Student Name");
            columns.add("DOB");
            columns.add("Course");
//            

            jTable1.setModel(new DefaultTableModel(rows, columns) {

            });
        } catch (SQLException ex) {
            Logger.getLogger(SearchStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

//        try {
//            ResultSetMetaData rsd = rs.getMetaData();
//            c = rsd.getColumnCount();
//            DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
//            dft.setRowCount(0);
//
//            while (rs.next()) {
//                Vector v2 = new Vector();
//                for (int i = 1; i <= c; i++) {
//                    v2.add(rs.getString("id"));
//                    v2.add(rs.getString("StudentName"));
//                    v2.add(rs.getString("DOB"));
//                    v2.add(rs.getString("Course"));
//                    v2.add(rs.getString("FatherName"));
//                    v2.add(rs.getString("MotherName"));
//                    v2.add(rs.getString("ContactNo"));
//                    v2.add(rs.getString("Gender"));
//                    v2.add(rs.getString("EMail"));
//                    v2.add(rs.getString("AdhaarCard"));
//                }
//                dft.addRow(v2);
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

  


    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
//        obj.conn();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
        
        System.out.println(id);
        String StudentName = Sname.getText();
        String FatherName = Fname.getText();
        String MotherName = Mname.getText();
        String DOfB = DOB.getText();
        String ContactNo = Contact.getText();
        String Email = mail.getText();
        String Gender = male1.isSelected()?"Male":"Female";
        String Address = address.getText();
        String AdhaarCard = ADCno.getText();
        String Marks10 = mark10.getText();
        String Marks12 = mark12.getText();
        String RollNo10 = roll10.getText();
        String RollNo12 = roll12.getText();
        String Course = (String) course.getSelectedItem();
        String Department = (String) course.getSelectedItem();
        try {
           // System.out.println(conn==null);
            pst =conn.prepareStatement("update Student_table set StudentName = ?, FatherName = ?, MotherName = ?, ContactNo =?, DOB =?, Gender =?, Email =?, Address =?, AdhaarCard =?, 10thMarks =?, 12thMarks =?, 10thRollNo =?, 12thRollNo =?, Course =?, Department =? where ID = ?");
            
            pst.setString(1, StudentName);
            pst.setString(2, FatherName);
            pst.setString(3, MotherName);
            pst.setString(4, ContactNo);
            pst.setString(5, DOfB);
            pst.setString(6, Gender);
            pst.setString(7, Email);
            pst.setString(8, Address);
            pst.setString(9, AdhaarCard);
            pst.setString(10, Marks10);
            pst.setString(11, Marks12);
            pst.setString(12, RollNo10);
            pst.setString(13, RollNo12);
            pst.setString(14, Course);
            pst.setString(15, Department);
            pst.setInt(16, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "record updated");
            refresh();
            tableupdate();

        } catch (SQLException ex) {
            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
        
        int dialogueresult = JOptionPane.showConfirmDialog(null, "Do you want to delete this record ?", "warning",JOptionPane.YES_NO_OPTION);
        if ( dialogueresult == JOptionPane.YES_NO_OPTION)
        {
        try {
            pst =conn.prepareStatement("Delete from Student_table where ID = ?");
             pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "record deleted");
            
            refresh();
            tableupdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(SearchStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        }  

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameDeiconified

    private void MnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnameActionPerformed

    private void ADCnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADCnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADCnoActionPerformed

    private void ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void male1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male1ActionPerformed
        // TODO add your handling code here:
        if (male1.isSelected()) {
            female.setSelected(false);
        }
    }//GEN-LAST:event_male1ActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        if (female.isSelected()) {
            male1.setSelected(false);
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       txtprint.setText("");
        tableclick();
       
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void mark12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark12ActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_courseActionPerformed

    private void DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_DeptActionPerformed

    private void roll10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roll10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roll10ActionPerformed

    private void mark10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark10ActionPerformed

    private void roll12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roll12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roll12ActionPerformed

    private void searchnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchnameMouseClicked
        // TODO add your handling code here:
        searchname.setText("");
    }//GEN-LAST:event_searchnameMouseClicked

    private void searchnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnameActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchnameActionPerformed

    private void searchnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchnameKeyReleased
        // TODO add your handling code here:
        String searchfield = searchname.getText();
        search(searchfield);
    }//GEN-LAST:event_searchnameKeyReleased

    private void DOBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOBMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DOBMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            txtprint.print();
        } catch (PrinterException ex) {
            Logger.getLogger(SearchStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADCno;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField DOB;
    private javax.swing.JComboBox<String> Dept;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Mname;
    private javax.swing.JTextField Sid;
    private javax.swing.JTextField Sname;
    private javax.swing.JButton Update;
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mail;
    private javax.swing.JRadioButton male1;
    private javax.swing.JTextField mark10;
    private javax.swing.JTextField mark12;
    private javax.swing.JTextField roll10;
    private javax.swing.JTextField roll12;
    private javax.swing.JTextField searchname;
    private javax.swing.JTextArea txtprint;
    // End of variables declaration//GEN-END:variables
}
